# Generated by Django 4.2 on 2023-04-23 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlines', '0004_country_modelairplane_city_airplane_airport_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('date_of_birth_day', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OS', 'On schedule'), ('CO', 'Check in open'), ('CC', 'Check in close'), ('LA', 'Landing'), ('DE', 'Departed'), ('IF', 'In flight'), ('AR', 'Arrived'), ('CA', 'Canceled')], default='OS', max_length=2)),
                ('departure', models.DateField(auto_now_add=True)),
                ('arrived', models.DateField(auto_now_add=True)),
                ('flight_number', models.CharField(max_length=100, unique_for_month=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.airplane')),
            ],
        ),
        migrations.AlterField(
            model_name='modelairplane',
            name='load_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='client',
            field=models.ManyToManyField(through='airlines.Ticket', to='airlines.client'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airlines.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='airlines.airport'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(choices=[('RUS_PASS', 'Russian passport')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('surname', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.client')),
            ],
        ),
    ]
