# Generated by Django 4.2 on 2023-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_alter_modelairplane_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
