# Generated by Django 4.2 on 2023-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0007_alter_airport_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelairplane',
            name='scheme',
            field=models.JSONField(default=dict),
        ),
    ]
