# Generated by Django 4.2 on 2023-05-14 16:27

import airlines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_alter_modelairplane_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelairplane',
            name='scheme',
            field=models.JSONField(default=dict, validators=[airlines.models.validate_airplane_scheme]),
        ),
    ]
