# Generated by Django 4.2 on 2023-05-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airlines', '0009_alter_modelairplane_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='client',
            field=models.ManyToManyField(through='airlines.Ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
