# Generated by Django 4.2 on 2023-05-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0010_alter_flight_client_alter_ticket_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='client',
            field=models.ManyToManyField(through='airlines.Ticket', to='airlines.client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.client'),
        ),
    ]
