# Generated by Django 4.2 on 2023-05-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0016_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrived',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
