# Generated by Django 4.2 on 2023-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0017_alter_flight_arrived_alter_flight_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=100),
        ),
    ]
