# Generated by Django 4.2 on 2023-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0018_alter_flight_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrived',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
