# Generated by Django 4.2 on 2023-05-15 08:16

import airlines.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0021_rename_client_flight_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.flight', validators=[airlines.models.validate_ticket_flight]),
        ),
    ]
