# Generated by Django 4.2 on 2023-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0022_alter_ticket_flight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'flight', 'client')},
        ),
    ]
