# Generated by Django 4.2 on 2023-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0023_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='prices',
            field=models.JSONField(default=dict),
        ),
    ]
