# Generated by Django 4.2 on 2023-05-15 10:46

import airlines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0024_flight_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='prices',
            field=models.JSONField(default=dict),
        ),
    ]
