# Generated by Django 4.2 on 2023-05-15 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0025_alter_flight_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrived',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flight',
            name='prices',
            field=models.JSONField(default=dict),
        ),
    ]
