# Generated by Django 4.2 on 2023-06-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0026_alter_flight_arrived_alter_flight_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('OS', 'On schedule'), ('CO', 'Check is open'), ('CC', 'Check is close'), ('LA', 'Landing'), ('DE', 'Departed'), ('IF', 'In flight'), ('AR', 'Arrived'), ('CA', 'Canceled')], default='OS', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'flight')},
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('CO', 'Confirmed'), ('CA', 'Cancelled')], default='WA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.ticket')),
            ],
        ),
    ]
