# Generated by Django 4.2 on 2023-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0027_alter_airplane_name_alter_flight_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.TextField(blank=True, null=True),
        ),
    ]
