# Generated by Django 4.2 on 2023-06-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0028_client_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
    ]
