# Generated by Django 4.2 on 2023-06-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0029_remove_client_first_name_remove_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='pay_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='airlines.ticket'),
        ),
    ]
