# Generated by Django 4.2 on 2023-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0031_alter_ticketbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
